<?php

/**
 * @param  Array 			A 2-dimensional array that contains data generated by Wigle Wifi.
 * @param  boolean 			returnAsJSON, true by default, false returns a 2-d array instead
 * @return String/Array 	JSON string or a 2-d array in this srtucture
 * 							Array([0]=>Array(
 * 								[SSID]=>'Network name',
 * 								[security]=>'security type',
 * 								[long]=>0.12345678,
 * 								[lat]=>0.12345678,
 * 								[accuracy]=>'in meters'),
 * 								...
 * 								);
 * 							Or the JSON equivalant.
 */
function generateMarkers( $table, $returnAsJSON = true ){
	$returnTable = array();
	$i = 0;
	foreach ($table as $nestedTable) {
		if ($nestedTable['Type'] == 'WIFI'){
			$returnTable[$i]["SSID"] = $nestedTable['SSID'];

			if (strpos($nestedTable['AuthMode'], 'WEP') !== false) {
				$returnTable[$i]["security"] = "WEP";
			} elseif (strpos($nestedTable['AuthMode'], 'WPS') !== false) {
				$returnTable[$i]["security"] = "WPS";
			} elseif (strpos($nestedTable['AuthMode'], 'WPA') !== false) {
				$returnTable[$i]["security"] = "WPA";
			}

			$returnTable[$i]["long"] = $nestedTable['CurrentLongitude'];
			$returnTable[$i]["lat"] = $nestedTable['CurrentLatitude'];
			$returnTable[$i]["accuracy"] = $nestedTable['Accuracy_meters'];
			$i++;
		}
	}
	if($returnAsJSON){
		return json_encode($returnTable);
	} else {
		return $returnTable;
	}
}

?>
