<?php

/**
 * @param  Array 			A 2-dimensional array that contains data generated by Wigle Wifi.
 * @param  boolean 			returnAsJSON, true by default, false returns a 2-d array instead
 * @return String/Array 	JSON string or a 2-d array in this srtucture
 * 							Array([0]=>Array(
 * 								[SSID]=>'Network name',
 * 								[security]=>'security type',
 * 								[long]=>0.12345678,
 * 								[lat]=>0.12345678,
 * 								[accuracy]=>'in meters'),
 * 								...
 * 								);
 * 							Or the JSON equivalant.
 */
function generateMarkers( $table, $returnAsJSON = true ){

	$returnTable = array();
	$i = 0;
	foreach ($table as $nestedTable) {
		if ($nestedTable[$_ENV['TYPE_COL']] == 'WIFI'){
			$returnTable[$i]['SSID'] = $nestedTable[$_ENV["SSID_COL"]];

			if (strpos($nestedTable[$_ENV['AUTHMODE_COL']], 'WEP') !== false) {
				$returnTable[$i]["security"] = "WEP";
			} elseif (strpos($_ENV["AUTHMODE_COL"], 'WPS') !== false) {
				$returnTable[$i]["security"] = "WPS";
			} elseif (strpos($_ENV["AUTHMODE_COL"], 'WPA') !== false) {
				$returnTable[$i]["security"] = "WPA";
			}

			$returnTable[$i]["long"] = $nestedTable[$_ENV["LONG_COL"]];
			$returnTable[$i]["lat"] = $nestedTable[$_ENV["LAT_COL"]];
			$returnTable[$i]["accuracy"] = $nestedTable[$_ENV["ACCURACY_COL"]];
			$i++;
		}
	}
	if($returnAsJSON){
		return json_encode($returnTable);
	} else {
		return $returnTable;
	}
}

function findCentreOfPoints( $table ){
	$xTotal = 0;
	$yTotal = 0;
	$count = 0;
	foreach ($table as $row) {
		$xTotal += $row["long"];
		$yTotal += $row["lat"];
		$count++; 
	}

	if( $count != 0)
		return array("long" => $xTotal/$count, "lat" => $yTotal/$count);

	return array("long" => 0, "lat" => 0);
}

?>
